spring.application.name=coffee-choc

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/coffeechoc
spring.datasource.username=postgres
spring.datasource.password=Super123!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Port (optionnel, 8080 par défaut)
server.port=8083
